### ISSUE TITLE
Netty Exception - io.netty.handler.codec.TooLongFrameException

### ISSUE THREAD

**Issue by jebbench** [msemys/esjc#2]
Using esjc 1.4.0 with EventStore 3.6.2.0 when running the code:
```
eventStore.appendToStream("user-".concat(key), ExpectedVersion.noStream(), Arrays.asList(
            EventData.newBuilder()
                .type("user_created")
                .jsonData(jsonObject.encode())
                .build()
        ));
```
I get the exception (it repeats until the application is stopped):
```
Generated: io.netty.util.internal.__matchers__.io.netty.buffer.ByteBufMatcher 
Generated: io.netty.util.internal.__matchers__.com.github.msemys.esjc.tcp.TcpPackageMatcher 
java.nio.ByteBuffer.cleaner(): available 
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. 
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 67108864: 1347703884 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:499)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:477)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:403)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jebbench** [comment]
I was using the wrong port :-(
1113 for the TCP interface, not 2113.
