### ISSUE TITLE
Creating a projection using the ProjectionManager is timing out

### ISSUE THREAD

**Issue by sanjeevp** [msemys/esjc#38]
```java
//given a projection manager and a query string
CreateOptions options = CreateOptions.newBuilder()
            .emit(true)
            .enabled(true)
            .trackEmittedStreams(false)
            .mode(ProjectionMode.CONTINUOUS).build();
try {
    manager.create("TestProjection",
                query,
                options).get(2L, TimeUnit.MINUTES);
} catch (InterruptedException | ExecutionException | TimeoutException e) {
    logger.info("Exception creating projection", e);  //This always times out
}
```
Response:
```
Exception creating projection
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	<...>
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.github.msemys.esjc.http.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:20)
	at com.github.msemys.esjc.http.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:12)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
```

However I tried it manually using AsyncHttpClient from Netty and it works fine.
```java
Request create = new RequestBuilder(HttpConstants.Methods.POST)
                .setUrl("http://localhost:2113/projections/continuous?name= TestProjection"
                    + "&type=JS&enabled=true"
                    + "&checkpoints=false&emit=true&trackemittedstreams=false")
                .setHeader("Authorization", "Basic YWRtaW46Y2hhbmdlaXQ=")
                .setHeader("Content-Type", "application/json")
                .setBody(query).build();

try {
    Response response = client.executeRequest(create).get();
    logger.info("response:" + response.getResponseBody());
} catch (InterruptedException e) {
    e.printStackTrace();
} catch (ExecutionException e) {
    logger.info("exception", e);
}
```
see response:
```
Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledSlicedByteBuf(freed))
POST /projections/continuous?name=TestProjection&type=JS&enabled=true&checkpoints=false&emit=true&trackemittedstreams=false HTTP/1.1
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=
Content-Type: application/json
content-length: 113
host: localhost:2113
accept: */*
user-agent: AHC/2.1

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Location: http://localhost:2113/projection/TestProjection?name=TestProjection&type=JS&enabled=true&checkpoints=false&emit=true&trackemittedstreams=false
Content-Type: application/json; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Tue, 19 Jun 2018 15:06:24 GMT
Content-Length: 50
Keep-Alive: timeout=15,max=100
```

This was tested against Event Store 4.0.3 and 4.1.1 and did not work in either version.

Other ProjectionManager API work fine, such as `getStatus` and `enable`.

**Comment by msemys** [comment]
It looks working for me and on travis. I've tested by running integration tests `com.github.msemys.esjc.projection.ITProjectionManager` with esjc 2.0.0 and es v4.1.0.
What esjc version you are running?
Could you enable http client logging `<logger name="com.github.msemys.esjc.http.HttpClient" level="TRACE" />` and re-run your test?

**Comment by sanjeevp** [comment]
So after I raised this I re-ran some tests and figured out what the problem was.  In my code I was testing to see if a projection existed and then creating it if it did not.  Here is the sample code that failed:

```java
final String projectionName = "TestProjection";

String query = "fromCategory(\"Test\")\n"
    + ".when({\n"
    + "   $any: function(state, event) {\n"
    + "       linkTo(\"TargetStream\", event);\n"
    + "   } \n"
    + "});";

manager.getStatus(projectionName).handle((status, throwable) -> {
    if (throwable != null) {

        if (throwable.getCause() instanceof ProjectionNotFoundException) {
            //projection does not exist yet so lets create it
            logger.info("Projection not found");
            CreateOptions options = CreateOptions.newBuilder()
                .emit(true)
                .enabled(true)
                .trackEmittedStreams(false)
                .mode(ProjectionMode.CONTINUOUS).build();


            return manager.create(projectionName, query, options)
                .handle((result, throwable2) -> {
                    if (throwable2 != null) {
                        if (throwable2.getCause() instanceof ProjectionConflictException) {
                            //we swallow this as another instance has already created this projection
                            logger.info("Got conflict on projection creation, looks like the projection '"
                                + projectionName + "' has already been created.");
                        } else {
                            logger.error("Got exception trying to create a projection", throwable2);
                            Throwables.throwIfUnchecked(throwable2);
                        }
                    }
                    return result;
                }).join();

        } else {
            logger.info("Exception when trying to get projection status", throwable);
            Throwables.throwIfUnchecked(throwable);
        }
    } else {
        logger.info("Projection: " + status.name + " Status:" + status.status + " lastCheckpoint:" + status.lastCheckpoint);
    }

    return null;
}).join();
```

Notice the `join()` on the create -> handle.  This was the issue.  Once I removed that `join()` it worked as I expected it to.

Thanks for responding so quickly.  I'll close it.
