### ISSUE TITLE
NullPointerException: connection is null

### ISSUE THREAD

**Issue by StephanPraetsch** [msemys/esjc#52]
Hi,

we use
```
                <groupId>com.github.msemys</groupId>
                <artifactId>esjc</artifactId>
                <version>2.1.0</version>
```

Sometimes a
```
java.lang.NullPointerException: connection is null
	at com.github.msemys.esjc.util.Preconditions.checkNotNull(Preconditions.java:7)
	at com.github.msemys.esjc.EventStoreTcp.gotoIdentificationPhase(EventStoreTcp.java:743)
	at com.github.msemys.esjc.EventStoreTcp.onAuthenticationCompleted(EventStoreTcp.java:677)
	at com.github.msemys.esjc.EventStoreTcp.access$800(EventStoreTcp.java:69)
	at com.github.msemys.esjc.EventStoreTcp$1.lambda$initChannel$0(EventStoreTcp.java:146)
	at com.github.msemys.esjc.tcp.handler.AuthenticationHandler.complete(AuthenticationHandler.java:95)
	at com.github.msemys.esjc.tcp.handler.AuthenticationHandler.channelRead0(AuthenticationHandler.java:44)
	at com.github.msemys.esjc.tcp.handler.AuthenticationHandler.channelRead0(AuthenticationHandler.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.github.msemys.esjc.tcp.handler.HeartbeatHandler.channelRead0(HeartbeatHandler.java:41)
	at com.github.msemys.esjc.tcp.handler.HeartbeatHandler.channelRead0(HeartbeatHandler.java:17)
``` 
is logged. I suppose it's caused by a restarted event store. Nevertheless a NPE indicates a bug in the software.

Will you please handle this differently to avoid a NPE?

**Comment by newson-synopsys** [comment]
My team is also experiencing this. It was more common when we had two ESJC connections at the same time in the same JVM, though we have deduplicated that connection and are still observing it. 

@msemys Do you remember why there is a checkNotNull on the connection in gotIdentificationPhase? https://github.com/msemys/esjc/blob/master/src/main/java/com/github/msemys/esjc/EventStoreTcp.java#L743

**Comment by msemys** [comment]
just to ensure that connection is not lost

**Comment by newson-synopsys** [comment]
@StephanPraetsch we just merged !59 (see above), can you confirm that this fixes the issue for you? If so you can close this issue :)
